import struct


# Type Tokens
BYTE_TYPE_TOKEN = "x"
CHAR_TYPE_TOKEN = "c"
SIGNED_CHAR_TYPE_TOKEN = "b"
UNSIGNED_CHAR_TYPE_TOKEN = "B"
BOOL_TYPE_TOKEN = "?"
SHORT_TYPE_TOKEN = "h"
UNSIGNED_SHORT_TYPE_TOKEN = "H"
INT_TYPE_TOKEN = "i"
UNSIGNED_INT_TYPE_TOKEN = "I"
LONG_TYPE_TOKEN = "l"
UNSIGNED_LONG_TYPE_TOKEN = "L"
LONG_LONG_TYPE_TOKEN = "q"
UNSIGNED_LONG_LONG_TYPE_TOKEN = "Q"
SSIZE_T_TYPE_TOKEN = "n"
SIZE_T_TYPE_TOKEN = "N"
FLOAT16_TYPE_TOKEN = "e"
FLOAT_TYPE_TOKEN = "f"
DOUBLE_TYPE_TOKEN = "d"
FLOAT_COMPLEX_TYPE_TOKEN = "F"
DOUBLE_COMPLEX_TYPE_TOKEN = "D"
VOID_PTR_TYPE_TOKEN = "P"

# Fixed and System-Dependent C Type Sizes via calcsize
SIZE_PAD_BYTE = struct.calcsize(BYTE_TYPE_TOKEN)
SIZE_CHAR = struct.calcsize(CHAR_TYPE_TOKEN)
SIZE_SIGNED_CHAR = struct.calcsize(SIGNED_CHAR_TYPE_TOKEN)
SIZE_UNSIGNED_CHAR = struct.calcsize(UNSIGNED_CHAR_TYPE_TOKEN)
SIZE_BOOL = struct.calcsize(BOOL_TYPE_TOKEN)
SIZE_SHORT = struct.calcsize(SHORT_TYPE_TOKEN)
SIZE_UNSIGNED_SHORT = struct.calcsize(UNSIGNED_SHORT_TYPE_TOKEN)
SIZE_INT = struct.calcsize(INT_TYPE_TOKEN)
SIZE_UNSIGNED_INT = struct.calcsize(UNSIGNED_INT_TYPE_TOKEN)
SIZE_LONG = struct.calcsize(LONG_TYPE_TOKEN)
SIZE_UNSIGNED_LONG = struct.calcsize(UNSIGNED_LONG_TYPE_TOKEN)
SIZE_LONG_LONG = struct.calcsize(LONG_LONG_TYPE_TOKEN)
SIZE_UNSIGNED_LONG_LONG = struct.calcsize(UNSIGNED_LONG_LONG_TYPE_TOKEN)
SIZE_SSIZE_T = struct.calcsize(SSIZE_T_TYPE_TOKEN)
SIZE_SIZE_T = struct.calcsize(SIZE_T_TYPE_TOKEN)
SIZE_FLOAT16 = struct.calcsize(FLOAT16_TYPE_TOKEN)
SIZE_FLOAT = struct.calcsize(FLOAT_TYPE_TOKEN)
SIZE_DOUBLE = struct.calcsize(DOUBLE_TYPE_TOKEN)
SIZE_FLOAT_COMPLEX = struct.calcsize(FLOAT_COMPLEX_TYPE_TOKEN)
SIZE_DOUBLE_COMPLEX = struct.calcsize(DOUBLE_COMPLEX_TYPE_TOKEN)
SIZE_VOID_PTR = struct.calcsize(VOID_PTR_TYPE_TOKEN)
